name: BlockHead
author: zand
main: com.zand.bukkit.blockhead.BlockHead
version: 0.3.1
commands:
  hat:
    description: Puts the block in-hand on your head
    usage: /hat
  blockhead:
    description:
    usage: